name: "RouteBastion_Development"

volumes:
  admin_cache_data:
    driver: local
  broker_cache_data:
    driver: local
  admin_db_data:
    driver: local
  broker_db_data:
    driver: local

services:
  #################################
  #          Admin API            #
  #################################
  admin-api:
    container_name: "admin-api"
    build:
      context: .
      dockerfile: apps/admin-api/dev.Dockerfile
    depends_on:
      admin-database:
        condition: service_healthy
      admin-cache:
        condition: service_healthy
    ports:
      - 3000:3000
      - 9229:9229 # Debugger
    volumes:
      - ./apps/admin-api:/app/apps/admin-api
      - /app/node_modules
      - /app/apps/admin-api/node_modules
      - /pnpm-store

  admin-database:
    image: dhi.io/postgres:18.1-alpine3.22-dev
    container_name: "admin-database"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=route_bastion_admin
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U docker -d route_bastion_admin'" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - "admin_db_data:/var/lib/postgresql/data"

  admin-cache:
    image: redis:7.4.2
    container_name: "admin-cache"
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - "admin_cache_data:/data"

  #################################
  #           Broker              #
  #################################
  broker:
    container_name: "broker"
    build:
      context: .
      dockerfile: apps/broker/build/dev.Dockerfile
    depends_on:
      broker-database:
        condition: service_healthy
      broker-cache:
        condition: service_healthy
    ports:
      - 8090:8090
      - 40000:40000 # Delve Debugger
    volumes:
      - ./apps/broker:/app/apps/broker
      - /go/pkg/mod
      - /root/.cache/go-build

  broker-database:
    image: dhi.io/postgres:18.1-alpine3.22-dev
    container_name: "broker-database"
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=route_bastion
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U docker -d route_bastion'" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - "broker_db_data:/var/lib/postgresql/data"

  broker-cache:
    image: redis:7.4.2
    container_name: "broker-cache"
    ports:
      - 6380:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - "broker_cache_data:/data"

  api-gateway:
    image: kong:3.9
    container_name: "api-gateway"
    depends_on:
      broker-database:
        condition: service_healthy
    environment:
      - "KONG_DATABASE=off"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
      - "KONG_ADMIN_GUI_URL=http://localhost:8002"
      - "KONG_DECLARATIVE_CONFIG=/kong/config.yaml"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
    volumes:
      - "./apps/broker/config/kong/dev/config.yaml:/kong/config.yaml"
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # API (Admin)
      - "8002:8002" # UI (Admin)
      - "8443:8443" # Proxy SSL (HTTPS)
      - "8444:8444" # API (Admin) (HTTPS)

  migrations:
    image: migrate/migrate
    container_name: "migrations"
    depends_on:
      broker-database:
        condition: service_healthy
    volumes:
      - "./apps/broker/sql/migrations:/migrations"
    command:
      [
        "-path",
        "migrations",
        "-database",
        "postgresql://docker:docker@broker-database:5432/route_bastion?sslmod\
          e=disable&search_path=public",
        "up",
      ]
    restart: on-failure
